<a href="https://colab.research.google.com/github/mmadeshwaran/Machine-Learning/blob/master/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sys
import numpy as np

print('Python:{}',sys.version)
print('Numpy: {}',np.__version__)

Python:{} 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Numpy: {} 1.16.5


In [4]:
#defining a scalar
x=6
x

6

In [6]:
#defining a vector
x=np.array((1,2,3))
x

array([1, 2, 3])

In [7]:
print('Vector Dimension: {}', x.shape)
print('Vector size: {}', x.size)

Vector Dimension: {} (3,)
Vector size: {} 3


In [8]:
#defining a matrix
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
print('Matrix Dimension: {}', x.shape)
print('Matrix size: {}', x.size)

Matrix Dimension: {} (3, 3)
Matrix size: {} 9


In [14]:
# define a matrix of a given dimension
x=np.ones((3,3,3))
print(x)
print('Matrix Dimension: {}', x.shape)
print('Matrix size: {}', x.size)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
Matrix Dimension: {} (3, 3, 3)
Matrix size: {} 27


In [15]:
# indexing
A=np.ones((5,5),dtype=np.int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [16]:
#indexing stars at 0
A[0,1]=2
print(A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
A[:,0]=3
print(A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [18]:
A[:,:]=7
print(A)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
