<a href="https://colab.research.google.com/github/mmadeshwaran/Machine-Learning/blob/master/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sys
import numpy as np

print('Python:{}',sys.version)
print('Numpy: {}',np.__version__)

Python:{} 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Numpy: {} 1.16.5


#defining a scalar

In [4]:

x=6
x

6

#defining a vector

In [6]:

x=np.array((1,2,3))
x

array([1, 2, 3])

In [7]:
print('Vector Dimension: {}', x.shape)
print('Vector size: {}', x.size)

Vector Dimension: {} (3,)
Vector size: {} 3


In [8]:
#defining a matrix
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
print('Matrix Dimension: {}', x.shape)
print('Matrix size: {}', x.size)

Matrix Dimension: {} (3, 3)
Matrix size: {} 9


# define a matrix of a given dimension

In [14]:

x=np.ones((3,3,3))
print(x)
print('Matrix Dimension: {}', x.shape)
print('Matrix size: {}', x.size)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
Matrix Dimension: {} (3, 3, 3)
Matrix size: {} 27


# indexing

In [15]:

A=np.ones((5,5),dtype=np.int)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [16]:
#indexing stars at 0
A[0,1]=2
print(A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# Assigning a column

In [17]:
A[:,0]=3
print(A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


# Setting all the values of a matrix to same value

In [18]:
A[:,:]=7
print(A)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


# Higher Dimension Matrix

In [19]:
A=np.ones((5,5,5), dtype=np.int)
print(A)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


# Assign first row a new value in the higher dimension matrix

In [20]:
A[:,0,0]=8
print(A)

[[[8 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[8 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[8 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[8 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[8 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


# Matrix Operation

In [22]:
A=np.matrix([[1,2],[4,5]])
B=np.ones((2,2),dtype=np.int)
print(A)
print(B)

[[1 2]
 [4 5]]
[[1 1]
 [1 1]]


# Matrix Addition

In [23]:
C=A+B
print(C)

[[2 3]
 [5 6]]


# Matrix Subtraction

In [24]:
C=A-B
print(C)

[[0 1]
 [3 4]]


# Matrix Multiplication

In [25]:
C=A*B
print(C)

[[3 3]
 [9 9]]


# Matrix Transpose

In [27]:
A=np.array(range(9))
print(A)
A=A.reshape(3,3)
print(A)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
B=A.T
print(B)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


# Transpose of Transpose will give original matrix

In [29]:
B=B.T
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Tensors

In [30]:
T=np.ones((3,3,3,3,3,3,3,3))
print(T.shape)
print(T.size)

(3, 3, 3, 3, 3, 3, 3, 3)
6561
